package com.demo.model;
// Generated 28-feb-2013 14:39:21 by Hibernate Tools 3.2.1.GA



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String codigoCliente;
     private String rucCliente;
     private String telefonoCliente;
     private Boolean estado;
     private String usuario;
     private String clave;
     private Boolean seguimiento;
     private Boolean despacho;

    public Cliente() {
    }

    public Cliente(String codigoCliente, String rucCliente, String telefonoCliente, Boolean estado, String usuario, String clave, Boolean seguimiento, Boolean despacho) {
       this.codigoCliente = codigoCliente;
       this.rucCliente = rucCliente;
       this.telefonoCliente = telefonoCliente;
       this.estado = estado;
       this.usuario = usuario;
       this.clave = clave;
       this.seguimiento = seguimiento;
       this.despacho = despacho;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(String codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public String getRucCliente() {
        return this.rucCliente;
    }
    
    public void setRucCliente(String rucCliente) {
        this.rucCliente = rucCliente;
    }
    public String getTelefonoCliente() {
        return this.telefonoCliente;
    }
    
    public void setTelefonoCliente(String telefonoCliente) {
        this.telefonoCliente = telefonoCliente;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Boolean getSeguimiento() {
        return this.seguimiento;
    }
    
    public void setSeguimiento(Boolean seguimiento) {
        this.seguimiento = seguimiento;
    }
    public Boolean getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Boolean despacho) {
        this.despacho = despacho;
    }




}


