package com.demo.model;
// Generated 28-feb-2013 14:39:21 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Boolean despacho;
     private Boolean ingresoD;
     private Boolean reporteD;
     private Boolean seguimiento;
     private Boolean ingresoS;
     private Boolean reporteS;
     private Boolean configuracion;
     private Boolean perfil;
     private Boolean usuario;
     private Boolean mantenimiento;
     private Boolean cliente;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Perfil() {
    }

    public Perfil(String descripcion, Boolean despacho, Boolean ingresoD, Boolean reporteD, Boolean seguimiento, Boolean ingresoS, Boolean reporteS, Boolean configuracion, Boolean perfil, Boolean usuario, Boolean mantenimiento, Boolean cliente, Set<Usuario> usuarios) {
       this.descripcion = descripcion;
       this.despacho = despacho;
       this.ingresoD = ingresoD;
       this.reporteD = reporteD;
       this.seguimiento = seguimiento;
       this.ingresoS = ingresoS;
       this.reporteS = reporteS;
       this.configuracion = configuracion;
       this.perfil = perfil;
       this.usuario = usuario;
       this.mantenimiento = mantenimiento;
       this.cliente = cliente;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Boolean despacho) {
        this.despacho = despacho;
    }
    public Boolean getIngresoD() {
        return this.ingresoD;
    }
    
    public void setIngresoD(Boolean ingresoD) {
        this.ingresoD = ingresoD;
    }
    public Boolean getReporteD() {
        return this.reporteD;
    }
    
    public void setReporteD(Boolean reporteD) {
        this.reporteD = reporteD;
    }
    public Boolean getSeguimiento() {
        return this.seguimiento;
    }
    
    public void setSeguimiento(Boolean seguimiento) {
        this.seguimiento = seguimiento;
    }
    public Boolean getIngresoS() {
        return this.ingresoS;
    }
    
    public void setIngresoS(Boolean ingresoS) {
        this.ingresoS = ingresoS;
    }
    public Boolean getReporteS() {
        return this.reporteS;
    }
    
    public void setReporteS(Boolean reporteS) {
        this.reporteS = reporteS;
    }
    public Boolean getConfiguracion() {
        return this.configuracion;
    }
    
    public void setConfiguracion(Boolean configuracion) {
        this.configuracion = configuracion;
    }
    public Boolean getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Boolean perfil) {
        this.perfil = perfil;
    }
    public Boolean getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Boolean usuario) {
        this.usuario = usuario;
    }
    public Boolean getMantenimiento() {
        return this.mantenimiento;
    }
    
    public void setMantenimiento(Boolean mantenimiento) {
        this.mantenimiento = mantenimiento;
    }
    public Boolean getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Boolean cliente) {
        this.cliente = cliente;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


