package com.demo.model;
// Generated 28-feb-2013 14:39:21 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private Integer idTransaccion;
     private String cliente;
     private String guiaClient;
     private String guiaTrans;
     private String origen;
     private String destino;
     private Integer nroBulto;
     private Double peso;
     private String via;
     private String docDespacho;
     private String transaccioncol;
     private Double pesoVolumen;
     private Date fechaRecojo;
     private Date horaRecojo;
     private Date fechaDespacho;
     private Date horaDespacho;
     private Date fechaDestino;
     private Date horaDestino;
     private Date fechaEntrega;
     private Date horaEntrega;
     private String personaEntrega;
     private String dniEntrega;
     private String observacion;
     private Boolean estado;

    public Transaccion() {
    }

    public Transaccion(String cliente, String guiaClient, String guiaTrans, String origen, String destino, Integer nroBulto, Double peso, String via, String docDespacho, String transaccioncol, Double pesoVolumen, Date fechaRecojo, Date horaRecojo, Date fechaDespacho, Date horaDespacho, Date fechaDestino, Date horaDestino, Date fechaEntrega, Date horaEntrega, String personaEntrega, String dniEntrega, String observacion, Boolean estado) {
       this.cliente = cliente;
       this.guiaClient = guiaClient;
       this.guiaTrans = guiaTrans;
       this.origen = origen;
       this.destino = destino;
       this.nroBulto = nroBulto;
       this.peso = peso;
       this.via = via;
       this.docDespacho = docDespacho;
       this.transaccioncol = transaccioncol;
       this.pesoVolumen = pesoVolumen;
       this.fechaRecojo = fechaRecojo;
       this.horaRecojo = horaRecojo;
       this.fechaDespacho = fechaDespacho;
       this.horaDespacho = horaDespacho;
       this.fechaDestino = fechaDestino;
       this.horaDestino = horaDestino;
       this.fechaEntrega = fechaEntrega;
       this.horaEntrega = horaEntrega;
       this.personaEntrega = personaEntrega;
       this.dniEntrega = dniEntrega;
       this.observacion = observacion;
       this.estado = estado;
    }
   
    public Integer getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(Integer idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getGuiaClient() {
        return this.guiaClient;
    }
    
    public void setGuiaClient(String guiaClient) {
        this.guiaClient = guiaClient;
    }
    public String getGuiaTrans() {
        return this.guiaTrans;
    }
    
    public void setGuiaTrans(String guiaTrans) {
        this.guiaTrans = guiaTrans;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public Integer getNroBulto() {
        return this.nroBulto;
    }
    
    public void setNroBulto(Integer nroBulto) {
        this.nroBulto = nroBulto;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public String getVia() {
        return this.via;
    }
    
    public void setVia(String via) {
        this.via = via;
    }
    public String getDocDespacho() {
        return this.docDespacho;
    }
    
    public void setDocDespacho(String docDespacho) {
        this.docDespacho = docDespacho;
    }
    public String getTransaccioncol() {
        return this.transaccioncol;
    }
    
    public void setTransaccioncol(String transaccioncol) {
        this.transaccioncol = transaccioncol;
    }
    public Double getPesoVolumen() {
        return this.pesoVolumen;
    }
    
    public void setPesoVolumen(Double pesoVolumen) {
        this.pesoVolumen = pesoVolumen;
    }
    public Date getFechaRecojo() {
        return this.fechaRecojo;
    }
    
    public void setFechaRecojo(Date fechaRecojo) {
        this.fechaRecojo = fechaRecojo;
    }
    public Date getHoraRecojo() {
        return this.horaRecojo;
    }
    
    public void setHoraRecojo(Date horaRecojo) {
        this.horaRecojo = horaRecojo;
    }
    public Date getFechaDespacho() {
        return this.fechaDespacho;
    }
    
    public void setFechaDespacho(Date fechaDespacho) {
        this.fechaDespacho = fechaDespacho;
    }
    public Date getHoraDespacho() {
        return this.horaDespacho;
    }
    
    public void setHoraDespacho(Date horaDespacho) {
        this.horaDespacho = horaDespacho;
    }
    public Date getFechaDestino() {
        return this.fechaDestino;
    }
    
    public void setFechaDestino(Date fechaDestino) {
        this.fechaDestino = fechaDestino;
    }
    public Date getHoraDestino() {
        return this.horaDestino;
    }
    
    public void setHoraDestino(Date horaDestino) {
        this.horaDestino = horaDestino;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Date getHoraEntrega() {
        return this.horaEntrega;
    }
    
    public void setHoraEntrega(Date horaEntrega) {
        this.horaEntrega = horaEntrega;
    }
    public String getPersonaEntrega() {
        return this.personaEntrega;
    }
    
    public void setPersonaEntrega(String personaEntrega) {
        this.personaEntrega = personaEntrega;
    }
    public String getDniEntrega() {
        return this.dniEntrega;
    }
    
    public void setDniEntrega(String dniEntrega) {
        this.dniEntrega = dniEntrega;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


